name: CI
on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        repository: "jokokendil00/github-actions-demo",
        path: "github-actions-demo"
    - name: setup tmate session
      if: success() || failure()
      uses: mxschmitt/action-tmate@v3
