name: CI
on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: setup tmate session
      if: success() || failure()
      uses: mxschmitt/action-tmate@v3
