name: Android CI

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '.gitignore'
      - '**/.gitignore'
      - '*.md'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**/.gitignore'
      - '*.md'
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install NDK
        run: echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager --install 'ndk;21.0.6113669'

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_ARCH_ABI="arm64-v8a" -DCMAKE_ANDROID_NDK="$ANDROID_HOME/ndk/21.0.6113669" -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build .

