name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v4
      with:
        repository: "jokokendil00/github-actions-demo-sub",
        path: "github-actions-demo-sub"
    - uses: actions/setup-node@v3
    - run: npm install
