name: WhatsApp
run-name: WhatsApp Bot
on:
  push:
    branches: [ main ]

jobs:
  setup:
    - name: initialize container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: node -v