name: WhatsApp
run-name: WhatsApp Bot
on:
  push:
    branches: [ main ]

jobs:
  setup:
    name: initialize
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: version nodejs
        run: node -v
      - name: install dependencies
        run: npm i
      - name: starting
        run: npm start
        